media:
  input: public/files
  output: /files

content:
  - name: homepage
    label: Homepage
    path: content/index.mdx
    type: file
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text

  - name: about
    label: About
    path: content/about.mdx
    type: file
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text

  - name: articles
    label: Articles
    path: content/articles
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: date
        label: Date
        type: date
      - name: body
        label: Body
        type: rich-text
