media: public/files
content:
  - name: homepage
    path: src/index.mdx
    label: Homepage
    type: file
    fields:
      - name: body
        label: Body
        type: rich-text
        options:
          image:
            path: public/files
            extensions: [ jpg, jpeg, png ]