import Head from "next/head";
import Link from "next/link";
import Transition from "../components/Transition";

// import Magnetic from "./components/Magnetic";
// import Image from "next/image";
import Hero from "../components/Hero";

export default function Services() {
    return (
        <>
            <Head>
                <title>swish</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Hero title="Works" image="files/manuel-weber-min.jpg" />

            <Transition>

                <h1>Whitelabel</h1>
                <p>Google Fonts makes it easy to bring personality and performance to your websites and products. Our robust catalog of open-source fonts and icons makes it easy to integrate expressive type and icons seamlessly — no matter where you are in the world.</p>
                <Link href="/">Go to index</Link>

                <h2>Headline 2</h2>
                <p>Google Fonts makes it easy to bring personality and performance to your websites and products. Our robust catalog of open-source fonts and icons makes it easy to integrate expressive type and icons seamlessly — no matter where you are in the world.</p>

                <h3>Headline 3</h3>
                <p>Google Fonts makes it easy to bring personality and performance to your websites and products. Our robust catalog of open-source fonts and icons makes it easy to integrate expressive type and icons seamlessly — no matter where you are in the world.</p>

                <h4>Headline 4</h4>
                <p>Google Fonts makes it easy to bring personality and performance to your websites and products. Our robust catalog of open-source fonts and icons makes it easy to integrate expressive type and icons seamlessly — no matter where you are in the world.</p>

                <h5>Headline 5</h5>
                <p>Google Fonts makes it easy to bring personality and performance to your websites and products. Our robust catalog of open-source fonts and icons makes it easy to integrate expressive type and icons seamlessly — no matter where you are in the world.</p>

                <h6>Headline 6</h6>
                <p>Google Fonts makes it easy to bring personality and performance to your websites and products. Our robust catalog of open-source fonts and icons makes it easy to integrate expressive type and icons seamlessly — no matter where you are in the world.</p>

            </Transition>
        </>
    );
}
